doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        driver: 'postgresql'
        server_version: '12'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Client:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/module/Client/src/Entity'
                prefix: 'Client\Entity'
                alias: Client
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/module/Core/src/Entity'
                prefix: 'Core\Entity'
                alias: Core
