version: '3.5'
services:
    frontend-nginx:
        build:
            context: ./frontend/docker
            dockerfile: nginx.docker
        volumes:
            - ./frontend:/app/frontend
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    node:
        image: node:11.13-alpine
        volumes:
            - ./frontend:/app/frontend
        working_dir: /app/frontend
        tty: true
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        volumes:
            - .:/app
        depends_on:
            - php-fpm
        ports:
            - "8081:80"
    php-fpm:
        build:
            context: ./docker/php/fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        depends_on:
            - postgres
    php-cli:
        build:
            context: ./docker/php/cli
            dockerfile: Dockerfile
        environment:
            APPLICATION_EXTERNAL_URL: "http://127.0.0.1:8081/api/v1"
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - postgres
    postgres:
        image: postgres:11.2-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: client
        ports:
            - "54321:5432"
    swagger-ui:
        image: swaggerapi/swagger-ui
        environment:
            SWAGGER_JSON: /app/openapi.yml
            APPLICATION_EXTERNAL_URL: "http://127.0.0.1:8081/api/v1"
        ports:
            - "8000:8080"
        volumes:
            - ./public/openapi.yml:/app/openapi.yml
volumes:
    postgres:
    composer: